# Copyright 2026 XTX Markets Technologies Limited
#
# SPDX-License-Identifier: GPL-2.0-or-later

obj-m += ternfs-policy-test.o
ternfs-policy-test-y := policy_test.o
ccflags-y += -I$(src)/.. -Wno-declaration-after-statement
