name: Build and Package EggsFS

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: prod
        options:
          - prod
          - staging
          - dev
jobs:

  build:
    runs-on: [self-hosted, restech]

    steps:
    - name: Checkout Eggs Repo
      uses: actions/checkout@v3
      with:
        repository: XTX/eggsfs
        path: 'eggs_repo'
    - name: Package EggsFS
      shell: bash
      working-directory: eggs_repo
      run: ./deploy/eggsctrl.py package --artifactory-host REDACTED --build-number $((${{ github.run_number }} + 1000))
