name: Build and Package EggsFS

on:
  workflow_dispatch:
    inputs:
      environment:
        required: true
        type: choice
        default: prod
        options:
          - prod
          - staging
          - dev
jobs:

  build:
    runs-on: [self-hosted, restech]

    steps:
    - uses: actions/checkout@v3
    - name: Package EggsFS
      shell: bash
      run: ./deploy/eggsctrl.py package --artifactory-host REDACTED --build-number $((${{ github.run_number }} + 1000))
